# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    
ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 100  # Hz
    info_file_name: task
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_pitch_joint
      - left_elbow_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_pitch_joint
      - right_elbow_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: dobot_atom

    # Control parameters
    home_pos: [ 0.0, 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    rest_pos: [ 0.1, 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]